arm64: mm: move dma_overlap() out of init section
Commit 19713fff6096 ("arm64: mmu: dma remap fail with 1GB block
mapping") added an out-of-tree function dma_overlap() marked __init.

dma_overlap() is only called from alloc_init_pud(), which at the time
was also marked __init.  However as part of the changes to implement
CONFIG_DEBUG_RODATA on ARM64, alloc_init_pud() was moved outside the
init section, making the call to dma_overlap() theoretically unsafe.

Fix this by moving dma_overlap() and all its dependent data outside of
the init/initdata section too.

Fixed "(

ERROR: modpost: Found 10 section mismatch(es).
To see full details build your kernel with:
'make CONFIG_DEBUG_SECTION_MISMATCH=y'
To build the kernel despite the mismatches, build with:
'make CONFIG_NO_ERROR_ON_MISMATCH=y'
(NOTE: This is not recommended)

")

Change-Id: I8f1a3d5aad23cc093f5a891ff7e9eb89cd7efad7
Signed-off-by: Greg Hackmann <ghackmann@google.com>
Signed-off-by: fadlyas07 <fadlyardhians@gmail.com>