scsi: ufs: Release clock if DMA map fails
[Fix commit 2ad318f9718bfda4fed04cbb2076062d1c457e48 "scsi: ufs: Release clock if DMA map fails"]

../drivers/scsi/ufs/ufshcd.c:2688:3: error: too few arguments to function 'ufshcd_release'
../drivers/scsi/ufs/ufshcd.c:1406:6: note: declared here

change it to false better than we revert it.
[Reference: https://github.com/chips-project/msm-4.14/commit/c9b485cb9b5aafaf61fe934f8224b5f1479818b9]

Change-Id: Ic1927c41823ba770ef2a709402286b01119311ae
Signed-off-by: fadlyas07 <fadlyardhians@gmail.com>